This project analyzes Indian IPO performance for retail ivestor.
How - collecting 200+ real IPOs comparing them 
PROCESS 
-- Data collection from the website 
-- SQL storage and cleaning 
-- python EDA and insights
-- PowerBI dashboard

In [1]:
!pip install selenium webdriver-manager

Requirement already satisfied: selenium in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (4.22.0)
Requirement already satisfied: webdriver-manager in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (4.0.2)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (2.2.1)
Requirement already satisfied: trio~=0.17 in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from selenium) (0.26.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from selenium) (2024.2.2)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from selenium) (4.12.2)
Requirement already satisfied: websocket-client>=1.8.0 in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: requests in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from webdriver-manager) (2.32.2)
Requirement already satisfied: python-dotenv in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from webdriver-manager) (1.2.2)
Requirement already satisfied: packaging in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from webdriver-manager) (24.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: sortedcontainers in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from trio~=0.17->selenium) (3.7)
Requirement already satisfied: outcome in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from trio~=0.17->selenium) (1.16.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from requests->webdriver-manager) (3.3.2)
Requirement already satisfied: pycparser in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.22)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)

driver.get("https://www.investorgain.com/report/ipo-performance-tracker/33/")

time.sleep(4)

page_html = driver.page_source
#print("Page title:", driver.title)

driver.quit()


soup = BeautifulSoup(page_html, "html.parser")
table = soup.find("table")
if table:
    print("Table found")
else:
    print("Table not found need to increase sleep time")

import requests
from bs4 import BeautifulSoup
#import pandas as pd

url = "https://www.chittorgarh.com/ipo/ipo_perf_tracker.asp?exchange=mainline&year=2025"
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}

response = requests.get(url, headers=headers)
print("Status:", response.status_code)

soup = BeautifulSoup(response.text, "html.parser")
tables = soup.find_all("table")
print(f"Tables found: {len(tables)}")

for i, t in enumerate(tables):
    rows = t.find_all("tr")
    print(f"Table {i+1} : {len(rows)} rows")
    if len(rows) > 1:
        print("Header:", rows[0].text.strip()[:200])
        print("Row 1 :", rows[1].text.strip()[:200])

In [17]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
from io import StringIO

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

url = "https://www.chittorgarh.com/ipo/ipo_perf_tracker.asp?exchange=mainline&year=2025"
driver.get(url)

wait = WebDriverWait(driver, 10)
wait.until(EC.presence_of_element_located((By.TAG_NAME, "table")))

page_table = driver.page_source

driver.quit()

df = pd.read_html(StringIO(page_table))[0]

print(df.head(5))
print("\nShape:",df.shape)

                                        Company Name  \
0  Gujarat Kidney & Super Speciality Ltd. IPO Det...
1  Stock Quotes & Charts:IPO Stock Quote & Charts...
2   KSH International Ltd. IPO Detail | Stock Quotes
3                                                NaN
4  ICICI Prudential Asset Management Co.Ltd. IPO ...

                                           Listed On  \
0                                  Tue, Dec 30, 2025
1  Stock Quotes & Charts:IPO Stock Quote & Charts...
2                                  Tue, Dec 23, 2025
3                                                NaN
4                                  Fri, Dec 19, 2025

                                         Issue Price  \
0                                               ₹114
1  Stock Quotes & Charts:IPO Stock Quote & Charts...
2                                               ₹384
3                                                NaN
4                                              ₹2165

                                   Listing Day Close  \
0                                            ₹104.54
1  Stock Quotes & Charts:IPO Stock Quote & Charts...
2                                               ₹355
3                                                NaN
4                                            ₹2585.9

                                    Listing Day Gain  \
0                                              -8.3%
1  Stock Quotes & Charts:IPO Stock Quote & Charts...
2                                             -7.55%
3                                                NaN
4                                             19.44%

                                       Current Price  \
0                                            ₹103.05
1  Stock Quotes & Charts:IPO Stock Quote & Charts...
2                                            ₹458.35
3                                                NaN
4                                            ₹2901.3

                                         Profit/Loss
0                                             -9.74%
1  Stock Quotes & Charts:IPO Stock Quote & Charts...
2                                             19.27%
3                                                NaN
4                                             34.03%

Shape: (216, 7)

Cleaning the collected Data

In [18]:
df.columns

Index(['Company Name', 'Listed On', 'Issue Price', 'Listing Day Close',
       'Listing Day Gain', 'Current Price', 'Profit/Loss'],
      dtype='object')

In [19]:
df

,Company Name,Listed On,Issue Price,Listing Day Close,Listing Day Gain,Current Price,Profit/Loss
0,Gujarat Kidney & Super Speciality Ltd. IPO Det...,"Tue, Dec 30, 2025",₹114,₹104.54,-8.3%,₹103.05,-9.74%
1,Stock Quotes & Charts:IPO Stock Quote & Charts...,Stock Quotes & Charts:IPO Stock Quote & Charts...,Stock Quotes & Charts:IPO Stock Quote & Charts...,Stock Quotes & Charts:IPO Stock Quote & Charts...,Stock Quotes & Charts:IPO Stock Quote & Charts...,Stock Quotes & Charts:IPO Stock Quote & Charts...,Stock Quotes & Charts:IPO Stock Quote & Charts...
2,KSH International Ltd. IPO Detail | Stock Quotes,"Tue, Dec 23, 2025",₹384,₹355,-7.55%,₹458.35,19.27%
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ICICI Prudential Asset Management Co.Ltd. IPO ...,"Fri, Dec 19, 2025",₹2165,₹2585.9,19.44%,₹2901.3,34.03%
...,...,...,...,...,...,...,...
211,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212,Standard Glass Lining Technology Ltd. IPO Deta...,"Mon, Jan 13, 2025",₹140,₹163.35,16.68%,₹135.98,-17.21%
213,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214,Indo Farm Equipment Ltd. IPO Detail | Stock Qu...,"Tue, Jan 7, 2025",₹215,₹273.69,27.3%,₹120.72,-44.02%
215,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df = df.dropna()
df

,Company Name,Listed On,Issue Price,Listing Day Close,Listing Day Gain,Current Price,Profit/Loss
0,Gujarat Kidney & Super Speciality Ltd. IPO Det...,"Tue, Dec 30, 2025",₹114,₹104.54,-8.3%,₹103.05,-9.74%
1,Stock Quotes & Charts:IPO Stock Quote & Charts...,Stock Quotes & Charts:IPO Stock Quote & Charts...,Stock Quotes & Charts:IPO Stock Quote & Charts...,Stock Quotes & Charts:IPO Stock Quote & Charts...,Stock Quotes & Charts:IPO Stock Quote & Charts...,Stock Quotes & Charts:IPO Stock Quote & Charts...,Stock Quotes & Charts:IPO Stock Quote & Charts...
2,KSH International Ltd. IPO Detail | Stock Quotes,"Tue, Dec 23, 2025",₹384,₹355,-7.55%,₹458.35,19.27%
4,ICICI Prudential Asset Management Co.Ltd. IPO ...,"Fri, Dec 19, 2025",₹2165,₹2585.9,19.44%,₹2901.3,34.03%
6,Park Medi World Ltd. IPO Detail | Stock Quotes,"Wed, Dec 17, 2025",₹162,₹147.95,-8.67%,₹200.11,23.49%
...,...,...,...,...,...,...,...
206,Laxmi Dental Ltd. IPO Detail | Stock Quotes,"Mon, Jan 20, 2025",₹428,₹550.55,28.63%,₹173.51,-59.42%
208,Capital Infra Trust IPO Detail,"Fri, Jan 17, 2025",₹99,₹99.02,0.02%,₹67.96,-31.35%
210,Quadrant Future Tek Ltd. IPO Detail | Stock Qu...,"Tue, Jan 14, 2025",₹290,₹444,53.1%,₹291.25,0.33%
212,Standard Glass Lining Technology Ltd. IPO Deta...,"Mon, Jan 13, 2025",₹140,₹163.35,16.68%,₹135.98,-17.21%
214,Indo Farm Equipment Ltd. IPO Detail | Stock Qu...,"Tue, Jan 7, 2025",₹215,₹273.69,27.3%,₹120.72,-44.02%

In [21]:
# Removing the "Stock Quotes & Charts" 

df = df[~df[df.columns[0]].str.contains("Stock Quotes & Charts", na=False)]
df

,Company Name,Listed On,Issue Price,Listing Day Close,Listing Day Gain,Current Price,Profit/Loss
0,Gujarat Kidney & Super Speciality Ltd. IPO Det...,"Tue, Dec 30, 2025",₹114,₹104.54,-8.3%,₹103.05,-9.74%
2,KSH International Ltd. IPO Detail | Stock Quotes,"Tue, Dec 23, 2025",₹384,₹355,-7.55%,₹458.35,19.27%
4,ICICI Prudential Asset Management Co.Ltd. IPO ...,"Fri, Dec 19, 2025",₹2165,₹2585.9,19.44%,₹2901.3,34.03%
6,Park Medi World Ltd. IPO Detail | Stock Quotes,"Wed, Dec 17, 2025",₹162,₹147.95,-8.67%,₹200.11,23.49%
8,Nephrocare Health Services Ltd. IPO Detail | S...,"Wed, Dec 17, 2025",₹460,₹471.25,2.45%,₹531.2,15.58%
...,...,...,...,...,...,...,...
206,Laxmi Dental Ltd. IPO Detail | Stock Quotes,"Mon, Jan 20, 2025",₹428,₹550.55,28.63%,₹173.51,-59.42%
208,Capital Infra Trust IPO Detail,"Fri, Jan 17, 2025",₹99,₹99.02,0.02%,₹67.96,-31.35%
210,Quadrant Future Tek Ltd. IPO Detail | Stock Qu...,"Tue, Jan 14, 2025",₹290,₹444,53.1%,₹291.25,0.33%
212,Standard Glass Lining Technology Ltd. IPO Deta...,"Mon, Jan 13, 2025",₹140,₹163.35,16.68%,₹135.98,-17.21%
214,Indo Farm Equipment Ltd. IPO Detail | Stock Qu...,"Tue, Jan 7, 2025",₹215,₹273.69,27.3%,₹120.72,-44.02%

In [22]:
df[df.columns[0]]

0      Gujarat Kidney & Super Speciality Ltd. IPO Det...
2       KSH International Ltd. IPO Detail | Stock Quotes
4      ICICI Prudential Asset Management Co.Ltd. IPO ...
6         Park Medi World Ltd. IPO Detail | Stock Quotes
8      Nephrocare Health Services Ltd. IPO Detail | S...
                             ...
206          Laxmi Dental Ltd. IPO Detail | Stock Quotes
208                       Capital Infra Trust IPO Detail
210    Quadrant Future Tek Ltd. IPO Detail | Stock Qu...
212    Standard Glass Lining Technology Ltd. IPO Deta...
214    Indo Farm Equipment Ltd. IPO Detail | Stock Qu...
Name: Company Name, Length: 108, dtype: object

In [30]:
df.loc[:, df.columns[0]] = df[df.columns[0]].str.replace(r"IPO Det.*", "", regex=True).str.strip()

In [31]:
df

,Company Name,Listed On,Issue Price,Listing Day Close,Listing Day Gain,Current Price,Profit/Loss
0,Gujarat Kidney & Super Speciality Ltd.,"Tue, Dec 30, 2025",₹114,₹104.54,-8.3%,₹103.05,-9.74%
2,KSH International Ltd.,"Tue, Dec 23, 2025",₹384,₹355,-7.55%,₹458.35,19.27%
4,ICICI Prudential Asset Management Co.Ltd.,"Fri, Dec 19, 2025",₹2165,₹2585.9,19.44%,₹2901.3,34.03%
6,Park Medi World Ltd.,"Wed, Dec 17, 2025",₹162,₹147.95,-8.67%,₹200.11,23.49%
8,Nephrocare Health Services Ltd.,"Wed, Dec 17, 2025",₹460,₹471.25,2.45%,₹531.2,15.58%
...,...,...,...,...,...,...,...
206,Laxmi Dental Ltd.,"Mon, Jan 20, 2025",₹428,₹550.55,28.63%,₹173.51,-59.42%
208,Capital Infra Trust,"Fri, Jan 17, 2025",₹99,₹99.02,0.02%,₹67.96,-31.35%
210,Quadrant Future Tek Ltd.,"Tue, Jan 14, 2025",₹290,₹444,53.1%,₹291.25,0.33%
212,Standard Glass Lining Technology Ltd.,"Mon, Jan 13, 2025",₹140,₹163.35,16.68%,₹135.98,-17.21%
214,Indo Farm Equipment Ltd.,"Tue, Jan 7, 2025",₹215,₹273.69,27.3%,₹120.72,-44.02%

In [38]:
df.columns = ["company", "listed_on", "issue_price", "listing_close", "listing_gain", "current_price", "profit_loss"]
df.columns

Index(['company', 'listed_on', 'issue_price', 'listing_close', 'listing_gain',
       'current_price', 'profit_loss'],
      dtype='object')

for col in ["issue_price", "listing_close", "current_price"]:
    df[col] = df[col].str.replace("₹", "").str.replace(",", "").str.strip()
    df[col] = pd.to_numeric(df[col], errors="coerce")
for col in ["listing_gain", "profit_loss"]:
    df[col] = df[col].str.replace("%", "").str.strip()
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [40]:
df

,company,listed_on,issue_price,listing_close,listing_gain,current_price,profit_loss
0,Gujarat Kidney & Super Speciality Ltd.,"Tue, Dec 30, 2025",114,104.54,-8.30,103.05,-9.74
2,KSH International Ltd.,"Tue, Dec 23, 2025",384,355.00,-7.55,458.35,19.27
4,ICICI Prudential Asset Management Co.Ltd.,"Fri, Dec 19, 2025",2165,2585.90,19.44,2901.30,34.03
6,Park Medi World Ltd.,"Wed, Dec 17, 2025",162,147.95,-8.67,200.11,23.49
8,Nephrocare Health Services Ltd.,"Wed, Dec 17, 2025",460,471.25,2.45,531.20,15.58
...,...,...,...,...,...,...,...
206,Laxmi Dental Ltd.,"Mon, Jan 20, 2025",428,550.55,28.63,173.51,-59.42
208,Capital Infra Trust,"Fri, Jan 17, 2025",99,99.02,0.02,67.96,-31.35
210,Quadrant Future Tek Ltd.,"Tue, Jan 14, 2025",290,444.00,53.10,291.25,0.33
212,Standard Glass Lining Technology Ltd.,"Mon, Jan 13, 2025",140,163.35,16.68,135.98,-17.21
214,Indo Farm Equipment Ltd.,"Tue, Jan 7, 2025",215,273.69,27.30,120.72,-44.02

In [42]:
!pip install sqlalchemy psycopg2

Requirement already satisfied: sqlalchemy in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (2.0.48)
Requirement already satisfied: psycopg2 in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\thanu\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.12.2)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [45]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:12345@localhost:5432/ipo_intelligence"
)
df.to_sql("ipo_data",           
          engine, 
          if_exists="replace",  
          index=False)          

print("Data stored successfully!")

Data stored successfully!

In [46]:
df_check = pd.read_sql("SELECT * FROM ipo_data LIMIT 5", engine)
print(df_check)

                                     company          listed_on  issue_price  \
0     Gujarat Kidney & Super Speciality Ltd.  Tue, Dec 30, 2025          114
1                     KSH International Ltd.  Tue, Dec 23, 2025          384
2  ICICI Prudential Asset Management Co.Ltd.  Fri, Dec 19, 2025         2165
3                       Park Medi World Ltd.  Wed, Dec 17, 2025          162
4            Nephrocare Health Services Ltd.  Wed, Dec 17, 2025          460

   listing_close  listing_gain  current_price  profit_loss
0         104.54         -8.30         103.05        -9.74
1         355.00         -7.55         458.35        19.27
2        2585.90         19.44        2901.30        34.03
3         147.95         -8.67         200.11        23.49
4         471.25          2.45         531.20        15.58

INSIGHTS OF THE IPO TABLE 
-- Market overview 
--Premium vs flat vs loss
--sell day vs hold 
-- best month
-- cheap vs expensive 
-- best and worst ipos


QUERIES FOR INSIGHTS 

Market overview 
SELECT COUNT(*) AS total_ipos,
    ROUND(AVG(listing_gain)::numeric, 2)  AS avg_gain,
	ROUND(MAX(listing_gain)::numeric, 2)  AS best_gain,
    ROUND(MIN(listing_gain)::numeric, 2)  AS worst_gain,
	Count (case when listing_gain >0 then 1 end ) as win ,
	count(case when listing_gain <0 then 1 end ) as loss,
	count(case when listing_gain =0 then 1 end ) as neutral,
	Round(count(case when listing_gain >0 then 1 end )*100/ count(*), 2) as winner_chance 
FROM ipo_data;

Premium vs flat vs loss

SELECT
    CASE
        WHEN listing_gain >= 20          THEN '1. Blockbuster (above 20%)'
        WHEN listing_gain BETWEEN 10 
             AND 20                      THEN '2. Good        (10% to 20%)'
        WHEN listing_gain BETWEEN 0 
             AND 10                      THEN '3. Mild        (0% to 10%)'
        WHEN listing_gain BETWEEN -10 
             AND 0                       THEN '4. Weak        (-10% to 0%)'
        ELSE                                  '5. Disaster    (below -10%)'
    END                                            AS performance_category,
    COUNT(*)                                       AS total_ipos,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) 
          OVER(), 1)                               AS percentage,
    ROUND(AVG(listing_gain)::numeric, 2)           AS avg_gain,
    ROUND(MAX(listing_gain)::numeric, 2)           AS best,
    ROUND(MIN(listing_gain)::numeric, 2)           AS worst
FROM ipo_data
GROUP BY performance_category
ORDER BY performance_category;

Sell day vs hold 
SELECT
    ROUND(AVG(listing_gain)::numeric, 2)  AS avg_sell_day1,
    ROUND(AVG(profit_loss)::numeric, 2)   AS avg_hold_today,
    ROUND((AVG(profit_loss) - AVG(listing_gain))::numeric, 2) AS extra_gain_by_holding
FROM ipo_data;

best month

SELECT
    EXTRACT(MONTH FROM listed_on::date)::INT  AS month_number,
    TO_CHAR(listed_on::date, 'Month')          AS month_name,
    COUNT(*)                                   AS total_ipos,
    ROUND(AVG(listing_gain)::numeric, 2)       AS avg_gain,
    COUNT(CASE WHEN listing_gain > 0 THEN 1 END) AS winners,
    COUNT(CASE WHEN listing_gain < 0 THEN 1 END) AS losers
FROM ipo_data
GROUP BY 
    EXTRACT(MONTH FROM listed_on::date),
    TO_CHAR(listed_on::date, 'Month')
ORDER BY avg_gain DESC;

cheap vs expensive 

SELECT
    CASE
        WHEN issue_price < 100          THEN '1. Low   (below ₹100)'
        WHEN issue_price BETWEEN 100 
             AND 500                    THEN '2. Mid   (₹100 to ₹500)'
        WHEN issue_price BETWEEN 500 
             AND 1000                   THEN '3. High  (₹500 to ₹1000)'
        ELSE                                 '4. Premium (above ₹1000)'
    END                                           AS price_band,
    COUNT(*)                                      AS total_ipos,
    ROUND(AVG(listing_gain)::numeric, 2)          AS avg_gain,
    ROUND(MAX(listing_gain)::numeric, 2)          AS best_gain,
    ROUND(MIN(listing_gain)::numeric, 2)          AS worst_gain,
    COUNT(CASE WHEN listing_gain > 0 THEN 1 END)  AS winners,
    COUNT(CASE WHEN listing_gain < 0 THEN 1 END)  AS losers
FROM ipo_data
GROUP BY price_band
ORDER BY price_band;

-- Top 10 Best IPOs
SELECT
    company,
    issue_price,
    listing_close,
    listing_gain,
    profit_loss
FROM ipo_data
ORDER BY listing_gain DESC
LIMIT 10;


-- Top 10 Worst IPOs
SELECT
    company,
    issue_price,
    listing_close,
    listing_gain,
    profit_loss
FROM ipo_data
ORDER BY listing_gain ASC
LIMIT 10;